#!/bin/sh
# Generated by agents-setup for agent '@AGENT@'. DO NOT EDIT.
# Root-owned by design: vendor self-updaters cannot overwrite this file.
# Regenerate with: provision-agents provision --all
#
# The real binary is located at RUNTIME by scanning TARGET_PATH (skipping
# the root-owned shim dir and this wrapper itself), falling back to the
# path recorded at provisioning time. Local installation updates of the
# agent binary therefore never break this wrapper.

set -eu

AGENT='@AGENT@'
CMDNAME='@COMMAND@'
SHIM_DIR='@SHIM_DIR@'
TARGET_PATH='@TARGET_PATH@'
FALLBACK='@TARGET@'

usage() {
    cat <<EOF
usage: $CMDNAME [--direct | --tmux [SESSION]] [ARGS...]

  (default)       run ARGS as agent account '$AGENT' via doas
  --direct        escape hatch: run the real binary as the current user,
                  bypassing doas and the agent account
  --tmux [NAME]   run as '$AGENT' inside tmux session NAME
                  (default: $CMDNAME-$AGENT); attaches if the session
                  already exists, so agent sessions survive disconnects
  --help          this help

Environment overrides:
  AGENT_WRAPPER_DIRECT=1        same as --direct
  AGENT_WRAPPER_TMUX=NAME       same as --tmux NAME
EOF
}

die() { printf '%s: %s\n' "$CMDNAME" "$*" >&2; exit 1; }

self=$(readlink -f "$0" 2>/dev/null || printf '%s' "$0")

# find_bin NAME: print the first executable NAME found in TARGET_PATH,
# skipping the shim dir and this wrapper itself; fall back to FALLBACK.
find_bin() {
    _needle=$1
    _old=$IFS
    IFS=:
    for _dir in $TARGET_PATH; do
        IFS=$_old
        [ -n "$_dir" ] || continue
        [ "$_dir" = "$SHIM_DIR" ] && continue
        _cand=$_dir/$_needle
        if [ -x "$_cand" ]; then
            _real=$(readlink -f "$_cand" 2>/dev/null || printf '%s' "$_cand")
            [ "$_real" = "$self" ] && continue
            printf '%s\n' "$_cand"
            return 0
        fi
    done
    IFS=$_old
    if [ -n "$FALLBACK" ] && [ -x "$FALLBACK" ]; then
        _real=$(readlink -f "$FALLBACK" 2>/dev/null || printf '%s' "$FALLBACK")
        [ "$_real" != "$self" ] && { printf '%s\n' "$FALLBACK"; return 0; }
    fi
    return 1
}

# quote_args: print args as a singly-quoted sh string for tmux.
quote_args() {
    _q=''
    for _a in ${1+"$@"}; do
        _q="$_q '$(printf '%s' "$_a" | sed "s/'/'\\\\''/g")'"
    done
    printf '%s' "$_q"
}

target=$(find_bin "$CMDNAME") ||
    die "cannot locate '$CMDNAME' (searched '$TARGET_PATH', fallback '$FALLBACK')"

# Script run by the agent's login shell (doas resets env and does not
# chdir). Start in the caller's directory when the agent may enter it,
# otherwise in the agent's home. $1 = caller cwd, $2 = binary, rest = args.
# shellcheck disable=SC2016
RUN_IN_CWD='cd "$1" 2>/dev/null || cd "$HOME" || exit 1; shift; exec "$@"'

MODE=doas
SESSION=${AGENT_WRAPPER_TMUX:-}
[ "${AGENT_WRAPPER_DIRECT:-}" = "1" ] && MODE=direct

if [ $# -gt 0 ]; then
    case $1 in
        --help|-h) usage; exit 0 ;;
        --direct)  MODE=direct; shift ;;
        --tmux)
            MODE=tmux; shift
            if [ $# -gt 0 ]; then
                case $1 in
                    --|-[a-zA-Z]*) ;;      # not a session name
                    *) SESSION=$1; shift ;;
                esac
            fi
            ;;
    esac
fi

case $MODE in
    direct)
        exec "$target" ${1+"$@"}
        ;;
    tmux)
        tmuxbin=$(find_bin tmux) || die "tmux not found (run bin/check-deps --install)"
        [ -n "$SESSION" ] || SESSION="$CMDNAME-$AGENT"
        if "$tmuxbin" has-session -t "$SESSION" 2>/dev/null; then
            exec "$tmuxbin" attach-session -t "$SESSION"
        fi
        inner="doas -u '$AGENT' -- /bin/sh -l -c '$RUN_IN_CWD' '$CMDNAME-wrapper'$(quote_args "$PWD" "$target" ${1+"$@"})"
        exec "$tmuxbin" new-session -s "$SESSION" "$inner"
        ;;
    *)
        exec doas -u "$AGENT" -- /bin/sh -l -c "$RUN_IN_CWD" \
            "$CMDNAME-wrapper" "$PWD" "$target" ${1+"$@"}
        ;;
esac
